# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d076d61d8949d31c2be43fcdd4b289ec6553538d1a59481581fd3b052d565d22655965450274b6127cda85c90e6db60dd9d9aa83ac6ac9b351dccd8884738dc

test:
  secret_key_base: 3f08cad1d0202853da2c58441ebd701927272aafe396db97fb46976930d639e981a48b7197bf628cfc5b2330d3fa138bc6298e72ecf8ae50b1cc7c9d51ede6f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
